package com.service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.12-patch-02
 * Tue Jun 05 19:41:46 PDT 2012
 * Generated source version: 2.2.12-patch-02
 * 
 */
 
@WebService(targetNamespace = "http://www.com.service", name = "BPMNWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface BPMNWebService {

    @WebResult(name = "price", targetNamespace = "")
    @RequestWrapper(localName = "calculatePolicyCost", targetNamespace = "http://www.com.service", className = "com.service.client.CalculatePolicyCost")
    @WebMethod
    @ResponseWrapper(localName = "calculatePolicyCostResponse", targetNamespace = "http://www.com.service", className = "com.service.client.CalculatePolicyCostResponse")
    public java.lang.Double calculatePolicyCost(
        @WebParam(name = "age", targetNamespace = "")
        int age,
        @WebParam(name = "numberOfAccidents", targetNamespace = "")
        int numberOfAccidents,
        @WebParam(name = "numberOfTickets", targetNamespace = "")
        int numberOfTickets,
        @WebParam(name = "creditScore", targetNamespace = "")
        int creditScore,
        @WebParam(name = "vehicleYear", targetNamespace = "")
        int vehicleYear,
        @WebParam(name = "policyType", targetNamespace = "")
        java.lang.String policyType
    );
}
