package com.service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.2.12-patch-02
 * Mon Jun 11 18:24:32 PDT 2012
 * Generated source version: 2.2.12-patch-02
 * 
 */
 
@WebService(targetNamespace = "http://www.com.service", name = "BPMNWebService")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface BPMNWebService {

    @WebResult(name = "price", targetNamespace = "http://www.com.service", partName = "price")
    @WebMethod
    public double calculatePolicyCost(
        @WebParam(partName = "age", name = "age")
        int age,
        @WebParam(partName = "numberOfAccidents", name = "numberOfAccidents")
        int numberOfAccidents,
        @WebParam(partName = "numberOfTickets", name = "numberOfTickets")
        int numberOfTickets,
        @WebParam(partName = "creditScore", name = "creditScore")
        int creditScore,
        @WebParam(partName = "vehicleYear", name = "vehicleYear")
        int vehicleYear,
        @WebParam(partName = "policyType", name = "policyType")
        java.lang.String policyType
    );
}
